### ISSUE TITLE
Where is core dry weight data?

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/bc-incubation2018#9]
Need to normalize fluxes by dry weight (I assume).

**Comment by bpbond** [comment]
I see the `wet_weights.csv` file, but nothing for dry end-of-experiment weights.

**Comment by AditiGit** [comment]
Yes. I only have dry weights for the end of the experiment when the cores were harvested. I planned to apply moisture content values to the wet_weights throughout the experiment. These won't be the exact numbers since the cores lost moisture, were wet-up to the field weight, lost moisture again, and so on. Wanted to ask you if this is standard procedure where end-of-experiment moisture content is applied as an average to the entire experiment. This does not sound right to me and I am open to suggestions about addressing this.

**Comment by bpbond** [comment]
Normally I think people normalize by dry mass regardless of anything else they do. Ignore the fluctuating wet weights for a moment; even if they were perfectly constant, we'd still have different amount of soil medium in each core, and want to know flux/g normally, where g is g dry mass, not just flux.

**Comment by AditiGit** [comment]
Okay, should be able to get this to you by end of work day. heading into the lab right now for some on and off lab work but will get this to you when i have down time in between.

**Comment by AditiGit** [comment]
Added dry weight values to "BeaverCreek_2018Incubation_PICARRO_Metadata.csv" file. I used the dry gravimetric moisture content from cores harvested at the end of the experiment. Since I sub-sampled for 2 heights, I used the average moisture content of two depths to represent moisture content of the core.

**Comment by bpbond** [comment]
I don't see a commit 😕   feel free to email if easier. Thanks!

**Comment by AditiGit** [comment]
yikes...updated the file on shared drive. I tried pushing the file but I don't seem to have permissions. Just emailing it to you to save time.

**Comment by bpbond** [comment]
Hi @AditiGit - looking at the file you sent and I'm quite confused. What I was expecting was a list giving one entry per _core_: its dry weight as measured at the end (typically) of the experiment. 

Instead, there's one entry per _measurement_, with a dry weight that varies, sometimes by by a LOT. 😕 How can the dry weight vary? I guess you're computing it from gravimetric water content (though no formula is visible). Why? How is gravimetric wc computed? The crazy-varying dry weight values will wildly throw off normalized fluxes, which is why I'm concerned.

Anyway, can you explain the steps that produced these values please?

**Comment by AditiGit** [comment]
Fixed. we were on the same page. Calculated gravimetric moisture content from the the core initial core moist weight (logic being that we ideally maintained weights throughout the experiment). Used formula Dry weight = moist weight/(1+wd) where wd is dry gravimetric moisture content. Emailed the file to you.
